In [13]:
import numpy as np

In [14]:
def jacobi(A, b, tolerance=1e-10):

    # find the shape of matrix A
    m, n = np.shape(A)

    # check if A is a square matrix
    if m != n:
        raise ValueError('Matrix A must be square')
    
    # check if A is diagonally dominant
    for i in range(n):
        sum_non_diag = 0
        for j in range(n):
            if i != j:
                sum_non_diag += abs(A[i,j])
        if sum_non_diag > abs(A[i,i]):
            raise ValueError('Matrix A must be diagonally dominant')

    # initial guess
    x = np.zeros(n)

    # new guess
    x_new = np.zeros(n)

    # initial error (set to large value to ensure loop runs at least once)
    error = np.inf

    # loop until error is less than tolerance
    while error > tolerance:

        for i in range(n):
            summation_term = 0
            for j in range(n):
                if i != j:
                    summation_term += A[i,j]*x[j]
            x_new[i] = (b[i] - summation_term)/A[i,i]

        # check for convergence
        error = abs(x - x_new).max()
        if error < tolerance:
            return x_new
        
        # update x
        x = np.copy(x_new)

In [15]:
def gauss_siedel(A, b, tolerance=1e-10):

    # find the shape of matrix A
    m, n = np.shape(A)

    # check if A is a square matrix
    if m != n:
        raise ValueError('Matrix A must be square')
    
    # check if A is diagonally dominant
    for i in range(m):
        sum_non_diag = 0
        for j in range(n):
            if i != j:
                sum_non_diag += abs(A[i,j])
        if sum_non_diag > abs(A[i,i]):
            # can implement a check if A is symmetric positive definite
            # because then Gauss-Seidel is guaranteed to converge if A is SPD
            # however, Jacobi is not guaranteed to converge if A is SPD
            raise ValueError('Matrix A must be diagonally dominant')

    # initial guess
    x = np.zeros(n)

    # initial error (set to large value to ensure loop runs at least once)
    error = np.inf

    # loop until error is less than tolerance
    while error > tolerance:

        x_old = np.copy(x) # to check for convergence

        for i in range(n):
            summation_term = 0
            for j in range(n):
                if i != j:
                    summation_term += A[i,j]*x[j]
            x[i] = (b[i] - summation_term)/A[i,i]

        # check for convergence
        error = abs(x - x_old).max()
        if error < tolerance:
            return x

In [16]:
def cholesky(A, b):

   # find the shape of matrix A 
    m, n = np.shape(A)

    # check if A is a square matrix
    if m != n:
        raise ValueError('Matrix A must be square')
    
    # check if A is symmetric positive definite
        # will implement this later

    # initialize L
    L = np.zeros((n,n))

    # find the Cholesky decomposition
    for i in range(n):
        for j in range(i+1):
            if i == j:
                summation_term = 0
                for k in range(i):
                    summation_term += L[i,k]**2
                L[i,i] = np.sqrt(A[i,i] - summation_term)
            else:
                summation_term = 0
                for k in range(j):
                    summation_term += L[j,k]*L[i,k]
                L[i,j] = (A[i,j] - summation_term)/L[j,j]
    
    # now solving for x
        # Ax = b; LL'x = b
        # Let y = L'x; Ly = b; L'x = y

    # solving Ly = b (using forward substitution)
    y = np.zeros(n)
    for i in range(n):
        summation_term = 0
        for j in range(i):
            summation_term += L[i,j]*y[j]
        y[i] = (b[i] - summation_term)/L[i,i]

    # solving L'x = y (using backward substitution)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        summation_term = 0
        for j in range(i+1, n):
            summation_term += L[j,i]*x[j]
        x[i] = (y[i] - summation_term)/L[i,i]

    return x

In [17]:
# diagonally dominant and symmetric positive definite matrix
A = np.array([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
    
b = np.array([1, 2, 3])

In [18]:
result_numpy = np.linalg.solve(A,b)
print(result_numpy)

[0.46428571 0.85714286 0.96428571]


In [19]:
result_cholesky = cholesky(A,b)
print(result_cholesky)

[0.46428571 0.85714286 0.96428571]


In [20]:
result_jacobi = jacobi(A,b)
print(result_jacobi)

[0.46428571 0.85714286 0.96428571]


In [21]:
result_gauss_siedel = gauss_siedel(A,b)
print(result_gauss_siedel)

[0.46428571 0.85714286 0.96428571]
